<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class FacultySeeder extends Seeder
{
    public function run(): void
    {
        $faculty = [
            [
                'custom_id' => 'FAC-2026-0001',
                'first_name' => 'Andrea',
                'last_name' => 'Salcedo',
                'middle_name' => 'Lopez',
                'email' => 'andrea.salcedo@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Mathematics',
                'contact_number' => '09170010001',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0002',
                'first_name' => 'Marco',
                'last_name' => 'Villareal',
                'middle_name' => 'Dizon',
                'email' => 'marco.villareal@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'English Communication',
                'contact_number' => '09170010002',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0003',
                'first_name' => 'Shaina',
                'last_name' => 'Ramirez',
                'middle_name' => 'Cruz',
                'email' => 'shaina.ramirez@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Science Explorations',
                'contact_number' => '09170010003',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0004',
                'first_name' => 'Julio',
                'last_name' => 'Navarro',
                'middle_name' => 'Santos',
                'email' => 'julio.navarro@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Technology and Livelihood Education',
                'contact_number' => '09170010004',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0005',
                'first_name' => 'Bianca',
                'last_name' => 'Ortiz',
                'middle_name' => 'Garcia',
                'email' => 'bianca.ortiz@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Physical Education and Health',
                'contact_number' => '09170010005',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0006',
                'first_name' => 'Carlos',
                'last_name' => 'Mendoza',
                'middle_name' => 'Reyes',
                'email' => 'carlos.mendoza@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Mathematics',
                'contact_number' => '09170010006',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0007',
                'first_name' => 'Kristine',
                'last_name' => 'De Jesus',
                'middle_name' => 'Santos',
                'email' => 'kristine.dejesus@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'English Communication',
                'contact_number' => '09170010007',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0008',
                'first_name' => 'Lorenzo',
                'last_name' => 'Castillo',
                'middle_name' => 'Diaz',
                'email' => 'lorenzo.castillo@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Science Explorations',
                'contact_number' => '09170010008',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0009',
                'first_name' => 'Mikaela',
                'last_name' => 'Soriano',
                'middle_name' => 'Lopez',
                'email' => 'mikaela.soriano@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Technology and Livelihood Education',
                'contact_number' => '09170010009',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0010',
                'first_name' => 'Paolo',
                'last_name' => 'Santiago',
                'middle_name' => 'Ramos',
                'email' => 'paolo.santiago@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Physical Education and Health',
                'contact_number' => '09170010010',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0011',
                'first_name' => 'Clarisse',
                'last_name' => 'Gonzales',
                'middle_name' => 'Aguilar',
                'email' => 'clarisse.gonzales@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Mathematics',
                'contact_number' => '09170010011',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0012',
                'first_name' => 'Hector',
                'last_name' => 'Velasco',
                'middle_name' => 'Torres',
                'email' => 'hector.velasco@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'English Communication',
                'contact_number' => '09170010012',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0013',
                'first_name' => 'Ina',
                'last_name' => 'Pineda',
                'middle_name' => 'Marquez',
                'email' => 'ina.pineda@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Science Explorations',
                'contact_number' => '09170010013',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0014',
                'first_name' => 'Jonas',
                'last_name' => 'Mercado',
                'middle_name' => 'Rivera',
                'email' => 'jonas.mercado@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Technology and Livelihood Education',
                'contact_number' => '09170010014',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0015',
                'first_name' => 'Larissa',
                'last_name' => 'Cabrera',
                'middle_name' => 'Santos',
                'email' => 'larissa.cabrera@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Physical Education and Health',
                'contact_number' => '09170010015',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0016',
                'first_name' => 'Miguel',
                'last_name' => 'Rosales',
                'middle_name' => 'Valdez',
                'email' => 'miguel.rosales@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Mathematics',
                'contact_number' => '09170010016',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0017',
                'first_name' => 'Nicole',
                'last_name' => 'Alonzo',
                'middle_name' => 'Delos Santos',
                'email' => 'nicole.alonzo@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'English Communication',
                'contact_number' => '09170010017',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0018',
                'first_name' => 'Orlando',
                'last_name' => 'San Juan',
                'middle_name' => 'Gutierrez',
                'email' => 'orlando.sanjuan@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Science Explorations',
                'contact_number' => '09170010018',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0019',
                'first_name' => 'Patricia',
                'last_name' => 'Lim',
                'middle_name' => 'Ocampo',
                'email' => 'patricia.lim@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Technology and Livelihood Education',
                'contact_number' => '09170010019',
                'status' => 'active',
            ],
            [
                'custom_id' => 'FAC-2026-0020',
                'first_name' => 'Rafael',
                'last_name' => 'Delos Reyes',
                'middle_name' => 'Garcia',
                'email' => 'rafael.delosreyes@amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'faculty',
                'department' => 'Physical Education and Health',
                'contact_number' => '09170010020',
                'status' => 'active',
            ],
        ];

        foreach ($faculty as $member) {
            DB::table('users')->updateOrInsert(
                ['custom_id' => $member['custom_id']],
                array_merge($member, [
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ])
            );
        }

        $this->command->info('✓ Created ' . count($faculty) . ' faculty records');
    }
}
