<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            // Grade 7 Students
            [
                'custom_id' => 'STU-2026-0001',
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'middle_name' => 'Santos',
                'email' => 'juan.delacruz@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 7',
                'lrn' => '123456789012',
                'contact_number' => '09171234567',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0002',
                'first_name' => 'Maria',
                'last_name' => 'Garcia',
                'middle_name' => 'Reyes',
                'email' => 'maria.garcia@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 7',
                'lrn' => '123456789013',
                'contact_number' => '09171234568',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0003',
                'first_name' => 'Pedro',
                'last_name' => 'Martinez',
                'middle_name' => 'Lopez',
                'email' => 'pedro.martinez@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 7',
                'lrn' => '123456789014',
                'contact_number' => '09171234569',
                'status' => 'active',
                'section_id' => null,
            ],
            
            // Grade 8 Students
            [
                'custom_id' => 'STU-2026-0004',
                'first_name' => 'Ana',
                'last_name' => 'Santos',
                'middle_name' => 'Cruz',
                'email' => 'ana.santos@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 8',
                'lrn' => '123456789015',
                'contact_number' => '09171234570',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0005',
                'first_name' => 'Carlos',
                'last_name' => 'Ramos',
                'middle_name' => 'Torres',
                'email' => 'carlos.ramos@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 8',
                'lrn' => '123456789016',
                'contact_number' => '09171234571',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0006',
                'first_name' => 'Sofia',
                'last_name' => 'Mendoza',
                'middle_name' => 'Pascual',
                'email' => 'sofia.mendoza@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 8',
                'lrn' => '123456789017',
                'contact_number' => '09171234572',
                'status' => 'active',
                'section_id' => null,
            ],
            
            // Grade 9 Students
            [
                'custom_id' => 'STU-2026-0007',
                'first_name' => 'Miguel',
                'last_name' => 'Rivera',
                'middle_name' => 'Flores',
                'email' => 'miguel.rivera@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 9',
                'lrn' => '123456789018',
                'contact_number' => '09171234573',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0008',
                'first_name' => 'Isabella',
                'last_name' => 'Fernandez',
                'middle_name' => 'Gutierrez',
                'email' => 'isabella.fernandez@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 9',
                'lrn' => '123456789019',
                'contact_number' => '09171234574',
                'status' => 'active',
                'section_id' => null,
            ],
            
            // Grade 10 Students
            [
                'custom_id' => 'STU-2026-0009',
                'first_name' => 'Gabriel',
                'last_name' => 'Navarro',
                'middle_name' => 'Castro',
                'email' => 'gabriel.navarro@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 10',
                'lrn' => '123456789020',
                'contact_number' => '09171234575',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0010',
                'first_name' => 'Lucia',
                'last_name' => 'Ramirez',
                'middle_name' => 'Hernandez',
                'email' => 'lucia.ramirez@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 10',
                'lrn' => '123456789021',
                'contact_number' => '09171234576',
                'status' => 'active',
                'section_id' => null,
            ],
            
            // Grade 11 Students (STEM)
            [
                'custom_id' => 'STU-2026-0011',
                'first_name' => 'Diego',
                'last_name' => 'Morales',
                'middle_name' => 'Silva',
                'email' => 'diego.morales@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 11',
                'lrn' => '123456789022',
                'contact_number' => '09171234577',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0012',
                'first_name' => 'Camila',
                'last_name' => 'Ortiz',
                'middle_name' => 'Rojas',
                'email' => 'camila.ortiz@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 11',
                'lrn' => '123456789023',
                'contact_number' => '09171234578',
                'status' => 'active',
                'section_id' => null,
            ],
            
            // Grade 12 Students (ABM)
            [
                'custom_id' => 'STU-2026-0013',
                'first_name' => 'Mateo',
                'last_name' => 'Vargas',
                'middle_name' => 'Pena',
                'email' => 'mateo.vargas@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 12',
                'lrn' => '123456789024',
                'contact_number' => '09171234579',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0014',
                'first_name' => 'Valentina',
                'last_name' => 'Romero',
                'middle_name' => 'Jimenez',
                'email' => 'valentina.romero@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 12',
                'lrn' => '123456789025',
                'contact_number' => '09171234580',
                'status' => 'active',
                'section_id' => null,
            ],
            
            // Additional Grade 7 Students
            [
                'custom_id' => 'STU-2026-0015',
                'first_name' => 'Ricardo',
                'last_name' => 'Bautista',
                'middle_name' => 'Villa',
                'email' => 'ricardo.bautista@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 7',
                'lrn' => '123456789026',
                'contact_number' => '09171234581',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0016',
                'first_name' => 'Elena',
                'last_name' => 'Cruz',
                'middle_name' => 'Santiago',
                'email' => 'elena.cruz@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 7',
                'lrn' => '123456789027',
                'contact_number' => '09171234582',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0017',
                'first_name' => 'Jasmine',
                'last_name' => 'Lopez',
                'middle_name' => 'Alvarez',
                'email' => 'jasmine.lopez@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 7',
                'lrn' => '123456789028',
                'contact_number' => '09171234583',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0018',
                'first_name' => 'Noah',
                'last_name' => 'Pascual',
                'middle_name' => 'Aquino',
                'email' => 'noah.pascual@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 7',
                'lrn' => '123456789029',
                'contact_number' => '09171234584',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0019',
                'first_name' => 'Alyssa',
                'last_name' => 'Villanueva',
                'middle_name' => 'Marquez',
                'email' => 'alyssa.villanueva@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 7',
                'lrn' => '123456789030',
                'contact_number' => '09171234585',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0020',
                'first_name' => 'Ethan',
                'last_name' => 'Soriano',
                'middle_name' => 'Molina',
                'email' => 'ethan.soriano@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 7',
                'lrn' => '123456789031',
                'contact_number' => '09171234586',
                'status' => 'active',
                'section_id' => null,
            ],

            // Additional Grade 8 Students
            [
                'custom_id' => 'STU-2026-0021',
                'first_name' => 'Bianca',
                'last_name' => 'Cabrera',
                'middle_name' => 'Diaz',
                'email' => 'bianca.cabrera@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 8',
                'lrn' => '123456789032',
                'contact_number' => '09171234587',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0022',
                'first_name' => 'Liam',
                'last_name' => 'Salazar',
                'middle_name' => 'Reyes',
                'email' => 'liam.salazar@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 8',
                'lrn' => '123456789033',
                'contact_number' => '09171234588',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0023',
                'first_name' => 'Nina',
                'last_name' => 'Castillo',
                'middle_name' => 'Gomez',
                'email' => 'nina.castillo@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 8',
                'lrn' => '123456789034',
                'contact_number' => '09171234589',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0024',
                'first_name' => 'Harper',
                'last_name' => 'Delgado',
                'middle_name' => 'Navarro',
                'email' => 'harper.delgado@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 8',
                'lrn' => '123456789035',
                'contact_number' => '09171234590',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0025',
                'first_name' => 'Caleb',
                'last_name' => 'Domingo',
                'middle_name' => 'Santos',
                'email' => 'caleb.domingo@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 8',
                'lrn' => '123456789036',
                'contact_number' => '09171234591',
                'status' => 'active',
                'section_id' => null,
            ],

            // Additional Grade 9 Students
            [
                'custom_id' => 'STU-2026-0026',
                'first_name' => 'Zoe',
                'last_name' => 'Pineda',
                'middle_name' => 'Valdez',
                'email' => 'zoe.pineda@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 9',
                'lrn' => '123456789037',
                'contact_number' => '09171234592',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0027',
                'first_name' => 'Lucas',
                'last_name' => 'Aguilar',
                'middle_name' => 'Rivera',
                'email' => 'lucas.aguilar@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 9',
                'lrn' => '123456789038',
                'contact_number' => '09171234593',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0028',
                'first_name' => 'Ariana',
                'last_name' => 'Reyes',
                'middle_name' => 'Sison',
                'email' => 'ariana.reyes@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 9',
                'lrn' => '123456789039',
                'contact_number' => '09171234594',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0029',
                'first_name' => 'Mason',
                'last_name' => 'Tolentino',
                'middle_name' => 'Cruz',
                'email' => 'mason.tolentino@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 9',
                'lrn' => '123456789040',
                'contact_number' => '09171234595',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0030',
                'first_name' => 'Sienna',
                'last_name' => 'Moreno',
                'middle_name' => 'Luna',
                'email' => 'sienna.moreno@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 9',
                'lrn' => '123456789041',
                'contact_number' => '09171234596',
                'status' => 'active',
                'section_id' => null,
            ],

            // Additional Grade 10 Students
            [
                'custom_id' => 'STU-2026-0031',
                'first_name' => 'Leah',
                'last_name' => 'Gonzales',
                'middle_name' => 'Suarez',
                'email' => 'leah.gonzales@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 10',
                'lrn' => '123456789042',
                'contact_number' => '09171234597',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0032',
                'first_name' => 'Julian',
                'last_name' => 'Lim',
                'middle_name' => 'Ortega',
                'email' => 'julian.lim@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 10',
                'lrn' => '123456789043',
                'contact_number' => '09171234598',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0033',
                'first_name' => 'Samantha',
                'last_name' => 'Herrera',
                'middle_name' => 'Yap',
                'email' => 'samantha.herrera@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 10',
                'lrn' => '123456789044',
                'contact_number' => '09171234599',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0034',
                'first_name' => 'Nathan',
                'last_name' => 'Padilla',
                'middle_name' => 'Flores',
                'email' => 'nathan.padilla@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 10',
                'lrn' => '123456789045',
                'contact_number' => '09171234600',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0035',
                'first_name' => 'Chloe',
                'last_name' => 'Manalo',
                'middle_name' => 'Perez',
                'email' => 'chloe.manalo@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 10',
                'lrn' => '123456789046',
                'contact_number' => '09171234601',
                'status' => 'active',
                'section_id' => null,
            ],

            // Additional Grade 11 Students
            [
                'custom_id' => 'STU-2026-0036',
                'first_name' => 'Aaron',
                'last_name' => 'Bacani',
                'middle_name' => 'David',
                'email' => 'aaron.bacani@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 11',
                'lrn' => '123456789047',
                'contact_number' => '09171234602',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0037',
                'first_name' => 'Mia',
                'last_name' => 'Serrano',
                'middle_name' => 'Tan',
                'email' => 'mia.serrano@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 11',
                'lrn' => '123456789048',
                'contact_number' => '09171234603',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0038',
                'first_name' => 'Adrian',
                'last_name' => 'Ocampo',
                'middle_name' => 'Bautista',
                'email' => 'adrian.ocampo@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 11',
                'lrn' => '123456789049',
                'contact_number' => '09171234604',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0039',
                'first_name' => 'Ivy',
                'last_name' => 'Garcia',
                'middle_name' => 'Quintana',
                'email' => 'ivy.garcia@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 11',
                'lrn' => '123456789050',
                'contact_number' => '09171234605',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0040',
                'first_name' => 'Bryan',
                'last_name' => 'Salonga',
                'middle_name' => 'Ramos',
                'email' => 'bryan.salonga@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 11',
                'lrn' => '123456789051',
                'contact_number' => '09171234606',
                'status' => 'active',
                'section_id' => null,
            ],

            // Additional Grade 12 Students
            [
                'custom_id' => 'STU-2026-0041',
                'first_name' => 'Hannah',
                'last_name' => 'Uy',
                'middle_name' => 'Dizon',
                'email' => 'hannah.uy@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 12',
                'lrn' => '123456789052',
                'contact_number' => '09171234607',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0042',
                'first_name' => 'Eli',
                'last_name' => 'Montes',
                'middle_name' => 'Sanchez',
                'email' => 'eli.montes@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 12',
                'lrn' => '123456789053',
                'contact_number' => '09171234608',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0043',
                'first_name' => 'Kara',
                'last_name' => 'Lacson',
                'middle_name' => 'Rizal',
                'email' => 'kara.lacson@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 12',
                'lrn' => '123456789054',
                'contact_number' => '09171234609',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0044',
                'first_name' => 'Owen',
                'last_name' => 'Silva',
                'middle_name' => 'Domingo',
                'email' => 'owen.silva@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 12',
                'lrn' => '123456789055',
                'contact_number' => '09171234610',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0045',
                'first_name' => 'Lara',
                'last_name' => 'Valencia',
                'middle_name' => 'Cortez',
                'email' => 'lara.valencia@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 12',
                'lrn' => '123456789056',
                'contact_number' => '09171234611',
                'status' => 'active',
                'section_id' => null,
            ],
            [
                'custom_id' => 'STU-2026-0046',
                'first_name' => 'Caleb',
                'last_name' => 'Rosales',
                'middle_name' => 'Dela Rosa',
                'email' => 'caleb.rosales@student.amore.edu',
                'password' => Hash::make('password123'),
                'account_type' => 'student',
                'grade_level' => 'Grade 12',
                'lrn' => '123456789057',
                'contact_number' => '09171234612',
                'status' => 'active',
                'section_id' => null,
            ],
        ];

        foreach ($students as $student) {
            DB::table('users')->updateOrInsert(
                ['custom_id' => $student['custom_id']],
                array_merge($student, [
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ])
            );
        }

        $this->command->info('✓ Created ' . count($students) . ' student records');
    }
}
